trigger:
  branches:
   include:
     - master
  paths:
    include:
      - CaffStore.Frontend/*

pr:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - task: UseDotNet@2
            inputs:
              packageType: 'sdk'
              version: '2.x'
          - task: SonarCloudPrepare@1
            inputs:
              SonarCloud: 'sonarCloud'
              organization: 'bodnarkevin'
              scannerMode: 'MSBuild'
              projectKey: 'caffly-frontend'
          - task: UseDotNet@2
            inputs:
              packageType: 'sdk'
              version: '3.1.x'
          - task: DotNetCoreCLI@2
            inputs:
              command: 'restore'
              feedsToUse: 'select'
          - task: DotNetCoreCLI@2
            inputs:
              command: 'build'
          - task: DotNetCoreCLI@2
            inputs:
              command: 'test'
          - task: UseDotNet@2
            inputs:
              packageType: 'sdk'
              version: '2.x'
          - task: SonarCloudAnalyze@1
          - task: SonarCloudPublish@1
            inputs:
              pollingTimeoutSec: '300'
  - stage: Docker
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest')
    jobs:
      - job: Docker
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'containerRegistry'
              repository: 'caffly-frontend'
              command: 'buildAndPush'
              Dockerfile: '$(Build.SourcesDirectory)/CaffStore.Frontend/Dockerfile'
              buildContext: '$(Build.SourcesDirectory)/CaffStore.Frontend'
              tags: 'latest'
  - stage: Deploy
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest')
    jobs:
      - job: Deploy
        steps:
          - checkout: none
          - task: AzureWebAppContainer@1
            inputs:
              azureSubscription: 'Azure for Students(96a88808-5be2-437f-8629-6c45fba7e081)'
              appName: 'caffly'
              containers: 'caffly.azurecr.io/caffly-frontend:latest'