trigger:
  branches:
   include:
     - master
  paths:
    include:
      - CIFFCAFFParser/*

pr:
- master

variables:
  workingDirectory: $(Build.SourcesDirectory)/CIFFCAFFParser
  buildWrapperOutput: $(workingDirectory)/bw-output

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - script: |
              sudo apt-get install build-essential
              sudo apt-get install valgrind
            displayName: Install dependencies
          - script: |
              make
            workingDirectory: $(workingDirectory)
            displayName: Build
          - script: |
              make check
            workingDirectory: $(workingDirectory)
            displayName: Valgrind
  - stage: SonarCloud
    jobs:
      - job: SonarCloud
        steps:
          - task: SonarCloudPrepare@1
            inputs:
              SonarCloud: 'sonarCloudParser'
              organization: 'bodnarkevin'
              scannerMode: 'CLI'
              configMode: 'manual'
              cliProjectKey: 'caffly-parser'
              cliSources: $(workingDirectory)
              extraProperties: |
                sonar.cfamily.build-wrapper-output=$(buildWrapperOutput)
                sonar.exclusions=**/lodepng.cpp
          - script: |
              curl --create-dirs -sSLo $HOME/.sonar/build-wrapper-linux-x86.zip https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
              unzip -o $HOME/.sonar/build-wrapper-linux-x86.zip -d $HOME/.sonar/
              export PATH=$HOME/.sonar/build-wrapper-linux-x86:$PATH

              build-wrapper-linux-x86-64 --out-dir $(buildWrapperOutput) make
            workingDirectory: $(workingDirectory)
            displayName: Build
          - task: SonarCloudAnalyze@1
          - task: SonarCloudPublish@1
            inputs:
              pollingTimeoutSec: '300'