trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Valgrind
    jobs:
      - job: Valgrind
        steps:
          - script: |
              sudo apt-get install build-essential
              sudo apt-get install valgrind
            displayName: Install dependencies
          - script: |
              make check
            workingDirectory: $(Build.SourcesDirectory)/CIFFCAFFParser
            displayName: Run Valgrind
